name = "gleam_qs"
version = "0.2.0"

description = "Parse and encode URL query strings"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam_qs" }

dependencies = { gleam_stdlib = "~> 0.28", gleeunit = "~> 0.10"}